version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: GMT
  open-pull-requests-limit: 10
  assignees:
  - l5x
  commit-message:
    prefix: fix
    include: scope
