language: bash
services: docker
env:
  - TEST_SUITE=epiloque.docker
  - TEST_SUITE=epiloque.duo_unix
  - TEST_SUITE=epiloque.epel
  - TEST_SUITE=epiloque.epiloque
  - TEST_SUITE=epiloque.ferm
  - TEST_SUITE=epiloque.logrotate
  - TEST_SUITE=epiloque.lvm
  - TEST_SUITE=epiloque.ntp
  - TEST_SUITE=epiloque.packagecloud
  - TEST_SUITE=epiloque.ssh
  - TEST_SUITE=epiloque.sudo
  - TEST_SUITE=epiloque.tunnelbroker
  - TEST_SUITE=epiloque.unattended-upgrades
  - TEST_SUITE=epiloque.virtualbox

script:
  - sudo pip install docker-py
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - gpg --keyserver pgp.mit.edu --recv-key 0x671C330913823C5B
  - ./manage ci

notifications:
  email:
    on_success: change
    on_failure: always

