---

- hosts: all
  # vars:
  #   duo_unix_duo_ikey: DIYTICSO5WN6AS3KN9P7
  #   duo_unix_duo_skey: eiooFW3PyFta0tfAIZ922sa5Iw7LuWkxtoNmXD3Q
  #   duo_unix_duo_host: api-20df6c01.duosecurity.com
  #   tunnelbroker_client_ipv6: 2001:470:1f12:852::2/64
  #   tunnelbroker_server_ipv4: 216.66.84.42
  #   tunnelbroker_server_ipv6: 2001:470:1f12:852::1
  roles:
  - epiloque
