version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    commit_message:
      prefix: "fix"
      include_scope: true
    default_assignees:
      - "l5x"
