name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
        - escapace.aws_cloudwatch
        - escapace.docker
        - escapace.dotfiles
        - escapace.dummy
        - escapace.duo_unix
        - escapace.epel
        - escapace.ferm
        - escapace.kresd
        - escapace.logrotate
        - escapace.lvm
        # - escapace.normalize
        - escapace.ntp
        - escapace.packagecloud
        - escapace.ssh
        - escapace.sudo
        - escapace.swap
        # - escapace.tor
        - escapace.tuned
        - escapace.tunnelbroker
        - escapace.unattended_upgrades
        # - escapace.virtualbox
        # - escapace.wireguard
    steps:
    - uses: actions/cache@v2.1.4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Setup Python environment
      uses: actions/setup-python@v2.2.1
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install requirements
      run: |
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
    - name: Run molecule test
      run: |
        molecule --version
        python3 --version
        export ANSIBLE_ROLES_PATH="$(readlink -f "./roles")"
        cd roles/${{ matrix.role }}
        molecule test
