name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - escapace.epel
          - escapace.sudo
    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Run molecule test
      run: |
        molecule --version
        python3 --version
        export ANSIBLE_ROLES_PATH="$(readlink -f "./roles")"
        cd roles/${{ matrix.role }}
        molecule test
